version: "3"
services:
  mongodb:
    image: "mongo:latest"
    restart: always
    volumes:
      - "$HOME/mongo_data/gablumDB:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: gablum
      MONGO_INITDB_ROOT_PASSWORD: GaB1uM
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "$HOME/rabbitmq_data/gablumMQ:/data/db"
    environment:
      RABBITMQ_DEFAULT_USER: gablum
      RABBITMQ_DEFAULT_PASS: GaB1uM
